version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: authlab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: authlab
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5432:5432"
    volumes:
      - authlab_pgdata:/var/lib/postgresql/data

volumes:
  authlab_pgdata: